### ISSUE TITLE
Dash doesn't build with the Bazel @af69e7a or later

### ISSUE THREAD

**Issue by achew22** [bazelbuild/dash#2]
➜  ~ bazel version
Build label: head (@af69e7a)
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Jan 17 08:30:02 2016 (1453019402)
Build timestamp: 1453019402
Build timestamp as int: 1453019402
➜  ~  cd /tmp
➜  /tmp  git clone https://github.com/bazelbuild/dash.git && cd dash && bazel build //:dash
Cloning into 'dash'...
remote: Counting objects: 44, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 44 (delta 3), reused 44 (delta 3), pack-reused 0
Unpacking objects: 100% (44/44), done.
Checking connectivity... done.
.........
ERROR: /tmp/dash/BUILD:3:1: every rule of type appengine_war implicitly depends upon the target '//third_party:apache_commons_collections',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 25.809s

**Comment by kchodorow** [comment]
See https://groups.google.com/d/msg/bazel-discuss/6lcvZo8f3xk/Wq9jHKFMFQAJ for a workaround.

**Comment by achew22** [comment]
Thanks Kristina! Unfortunately I'm still stuck. When I build and deploy to appengine, I get the rather cryptic error message: "The server encountered an error and could not complete your request." After looking in the logs I get "Unsupported major.minor version 52.0" which the internet assures me means that AppEngine is expecting a Java 7 app and this is a Java 8 app. Do you have any oneliners to fix that?

**Comment by achew22** [comment]
Actually the [Bazel blog](http://bazel.io/blog/2015/07/08/Java-Configuration.html) said exactly how to do this. Thanks whomever wrote that!

```sh
blaze build --javacopt="-target 7" --javacopt="-source 7" //:dash
```

**Comment by kchodorow** [comment]
Cool, that was @damienmg :)
